using System;
using RT.Util.Consoles;

namespace Qoph
{
    static class SpecialNames
    {
        public static void Find()
        {
            var (output, allFound) = WordSearch.Run(
                gridChars: "AUCOWXOYCURTISSACXSREGNARREXOPRHAEMIRPXUMITPOOURLTNINTESMAACNCTSTXEXAIHSHBXXXHETERMINATORBANVNBMDRNEQDOALROAOXEOEKGXENHXTRDJTUCPIEITAACEREAMLOURHLDHXKRIRNABCSKTLNCLKOSGANDXLFIEXEINBENITOMUSXOLINIOXODZILLAMNLKCGCWDNXAPOLAEIXOHXTHXROCKOJABALTPNAGOHKXUHLWJNN",
                width: 15, height: 17, consoleOutput: true,
                "AARONXARTER,ABRAHAXLINCOLN,BENITOMUSXOLINI,BILLXNDTED,BLUEMEXNIE,BLXCKKNIGHT,BXTMAN,CAXTAINKIRK,CHUCXNORRIS,COWXOYCURTIS,DOCOCX,GANDXLF,HUXKHOGAN,JAMXITHEGENIE,JAXKIECHAN,LOPAX,OPTIMUXPRIME,POXERRANGERS,ROBOCXP,SHAQXILLEONEAL,SPOCX,SUPERMXN,THXROCK,XARTHVADER,XHETERMINATOR,XNDIANAJONES,XODZILLA".Split(','));

            ConsoleUtil.WriteLine(output);
            Console.WriteLine(allFound);
        }
    }
}